### ISSUE TITLE
Small errors in the display of saving throws + animal handling proficiency isn't working

### ISSUE THREAD

**Issue by StephaneBau** [Dschaykib/kankaTemplate#10]
Hello again!

I noticed that the saving throws are calculated correctly but they don't appear as being "proficient" (circle isn't filled in black).
Also, the animal handling proficiency isn't calculated nor displayed as proficient.
![Capture](https://user-images.githubusercontent.com/36532123/115766336-25445300-a3a8-11eb-9a96-480fe86a213b.JPG)
![Capture2](https://user-images.githubusercontent.com/36532123/115766466-4f961080-a3a8-11eb-873d-9c53e2f85363.JPG)
![Capture3](https://user-images.githubusercontent.com/36532123/115766608-73f1ed00-a3a8-11eb-9dbe-bfdfc5152de8.JPG)

Thank you for your help in advance, I repeat that I really appreciate that you worked on this!

**Comment by Dschaykib** [comment]
With the new version, I had to change the attribute's names. Kanka uses a new syntax and the [blade engine](https://marketplace.kanka.io/helpers/template-html). In this syntax i cannot use spaces within the names anymore.

You have two options now:

1. either, save your values elsewhere, delete all attributes and than apply the template again to get the new spelling of the attributes.
2. or you change the names your self and replace all spaces with underscores. (eg "Wisdom Save" -> "Wisdom_Save"). During this change i also adjusted "AnimalHandling" to the same style "Animal_Handling". Also "SleightofHand" is now "Sleight_of_Hand".

If you want a full list of all used attribute names, you can check them [here](https://github.com/Dschaykib/kankaTemplate/blob/885cc1b43ee01101e1427d13fdc50b222257b1e5/templates/DnD5e/new5eCharacter.html#L338-L458).

**Comment by Dschaykib** [comment]
Also, if you have any wishes on how to improve the template or ideas for new ones, let me know and I will see what (and when) I could do :)

**Comment by StephaneBau** [comment]
Thank you, indeed it helped, I understand better how it works!

I could maybe help you translate it to French if you're up for it, that
would be great.
If that's something interesting for you, I will probably just edit the
github HTML/CSS by just changing all the relevant names and send you the
edited version by e-mail.

Le jeu. 22 avr. 2021 à 23:04, Jakob Gepp ***@***.***> a
écrit :

**Comment by Dschaykib** [comment]
I mean, since the file are up, you could just change the variables and the display to french and then upload it your self to kanka's marketplace :) that way, if there are questions about the french wording, I would not have to refer to you :) 

If you like you can add a pull request here and add a folder for the french version. If there will be any format changes and so on, I will take care of them.
