### ISSUE TITLE
Filling the spell field attribute is then displayed in the attacks field

### ISSUE THREAD

**Issue by StephaneBau** [Dschaykib/kankaTemplate#8]
Hello! 
When I fill in the attribute corresponding to spells, it gets displayed at the wrong place on the sheet.

Also, taking the time to thank you for all this!
![Capture](https://user-images.githubusercontent.com/36532123/115586652-1c328380-a2cd-11eb-85e3-c986a6455107.JPG)
![Capture2](https://user-images.githubusercontent.com/36532123/115586661-1e94dd80-a2cd-11eb-9688-b0c01bdd9a79.JPG)

**Comment by Dschaykib** [comment]
Hey, thanks for the feedback!
Question: where did you expect the spell to be placed at?
Because the I think the problem is not the placement of the spell, but rather the placement of the title "spellcasting". Since all titles are below their entries and should be at the bottom.

That said, i will have a look, too. If you have more feedback or comments, let me know!

**Comment by StephaneBau** [comment]
Hello ! 

Oh indeed, I understand better now what you did!
I got confused because in the attributes, there is both "attacks" and "spells" And I thought they both brought me to the same location by mistake.
![Capture3](https://user-images.githubusercontent.com/36532123/115603970-1b0b5180-a2e1-11eb-9f99-3a2454a37e99.JPG)

It didn't occur to me that it was probably done on purpose.

Regards, 
Stéphane

**Comment by Dschaykib** [comment]
well... i had a look and the spells are fine.... but the attacks are in the wrong place :D

I am working on a fix, so that spells have their own box below the attacks.

**Comment by Dschaykib** [comment]
@StephaneBau I fixed the order and also included the new blade syntax for kanka. the new plugin will be hopefully reviewed and available soon! :)

**Comment by StephaneBau** [comment]
Amazing work, it looks perfect now!
Good job :)

Le jeu. 22 avr. 2021 à 09:31, Jakob Gepp ***@***.***> a
écrit :
